#!/bin/bash
clear
tput cup 10 30
echo  -n "Enter the directory to be unexported:"
read  export
tput cup 11 30
#mkdir -v $export
chmod 777 $export
echo -n "                       "
grep -v $export /etc/exports >/root/bin/abc
cp /root/bin/abc /etc/exports
#echo $export  "(rw)">>/etc/exports

