#!/bin/bash
clear
tput cup 10 30
echo  -n "Insert the export dir"
read  export
tput cup 11 30
mkdir -v $export
chmod 777 $export
echo -n "                       "
echo $export "(rw)" >> /etc/exports

