#!/bin/bash
clear
tput cup 10 30
echo -n "Enter the host server:"
read ip
tput cup 11 30
echo -n "Enter the dir to mount upon:"
read dir
tput cup 12 30
mkdir -v $dir
tput cup 13 30
echo -n "The host dir to be mounted"
read hostdir
unmount -t nfs $ip:$hostdir $dir
 
